### ISSUE TITLE
因为HealthKit导致苹果审核失败

### ISSUE THREAD

**Issue by tanranran** [MxABC/LBXPermission#8]
![image](https://user-images.githubusercontent.com/5227840/56856958-ff426e80-6998-11e9-8601-2c7c96bfb91a.png)

**Comment by MxABC** [comment]
如果不需要健康权限，就不要包含这个权限代码，单独安装需要的步伐

**Comment by tanranran** [comment]
我的错，用的比较早，是直接 pod  LBXPermission 方式引用的。。
